### PR TITLE
Fix small bugs preventing workers from communicating over HTTPS

### PR DESCRIPTION
**Pull request by prsutherland**

### CODE REVIEW

**Comment by vikram-narayan** [comment]
lgtm

**Comment by cawallin** [comment]
This PR seems similar to https://github.com/prestodb/presto/pull/6682 -- it's not merged to prestodb yet, but it's available in the 157-t release of the Teradata distribution for Presto

**Comment by prsutherland** [comment]
@cawallin https://github.com/prestodb/presto/pull/6682 Looks much more robust. I'll defer to that PR. Thank you!

**Comment by cawallin** [comment]
No problem, glad to help out :)

**Pull request closed without merging**
